a = input('возраст пользователя: ')
b = input('пол пользователя: ')
c = input('имя пользователя: ')
d = input('город пользователя: ')
e = input('в каком классе пользователь учится: ')
print(a)
print(b)
print(c)
print(d)
print(e)